/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package licneFinansije.gui;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;

import licneFinansije.Serijalizacija;
import licneFinansije.korisnik.Korisnik;

/**
 *
 * @author Strahinja
 */
public class Registracija extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registracija.class.getName());

    /**
     * Creates new form Registracija
     */
    public Registracija() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistracija = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        unosIme = new javax.swing.JTextField();
        unosPrezime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        unosDatum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        unosUserName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        unosLozinka = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        ponovniUnosLozinke = new javax.swing.JPasswordField();
        dugmeRegistracija = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        panelRegistracija.setBackground(new java.awt.Color(247, 250, 254));
        panelRegistracija.setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRACIJA");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Ime:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("Prezime:");

        unosDatum.setToolTipText("format: dd.mm.yyyy.");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Datum rođenja:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("Korisničko ime:");

        unosUserName.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("Lozinka:");

        unosLozinka.addActionListener(this::unosLozinkaActionPerformed);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setText("Ponovite lozinku:");

        ponovniUnosLozinke.addActionListener(this::ponovniUnosLozinkeActionPerformed);

        dugmeRegistracija.setBackground(new java.awt.Color(123, 173, 227));
        dugmeRegistracija.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dugmeRegistracija.setForeground(new java.awt.Color(255, 255, 255));
        dugmeRegistracija.setText("Registracija");
        dugmeRegistracija.addActionListener(this::dugmeRegistracijaActionPerformed);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Već ste registrovani? PRIJAVA");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRegistracijaLayout = new javax.swing.GroupLayout(panelRegistracija);
        panelRegistracija.setLayout(panelRegistracijaLayout);
        panelRegistracijaLayout.setHorizontalGroup(
            panelRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistracijaLayout.createSequentialGroup()
                .addGroup(panelRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistracijaLayout.createSequentialGroup()
                        .addGroup(panelRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRegistracijaLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(panelRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistracijaLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(79, 79, 79)
                                        .addComponent(unosDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistracijaLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(79, 79, 79)
                                        .addComponent(unosPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistracijaLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(79, 79, 79)
                                        .addComponent(unosIme, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistracijaLayout.createSequentialGroup()
                                        .addGroup(panelRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(79, 79, 79)
                                        .addGroup(panelRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(unosUserName)
                                                .addComponent(unosLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(ponovniUnosLozinke, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(panelRegistracijaLayout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addComponent(dugmeRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addGroup(panelRegistracijaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistracijaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(201, 201, 201)))))
                .addContainerGap())
        );
        panelRegistracijaLayout.setVerticalGroup(
            panelRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistracijaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(panelRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(unosIme, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(unosPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(unosDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(unosUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(unosLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(ponovniUnosLozinke, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dugmeRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegistracija, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRegistracija, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unosLozinkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unosLozinkaActionPerformed
        //  add your handling code here:
    }//GEN-LAST:event_unosLozinkaActionPerformed

    private void ponovniUnosLozinkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponovniUnosLozinkeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponovniUnosLozinkeActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        new Prijava().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void dugmeRegistracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dugmeRegistracijaActionPerformed
        String ime=unosIme.getText();
        String prezime=unosPrezime.getText();
        String datumTekst=unosDatum.getText();
        char [] lozinkaNiz=unosLozinka.getPassword();
        String lozinka=new String(lozinkaNiz);
        char [] lozinkaNiz2=ponovniUnosLozinke.getPassword();
        String lozinkaProvera=new String(lozinkaNiz2);
        String userName=unosUserName.getText();
        LocalDate datum=null;
        try {
        datum = LocalDate.parse(datumTekst, DateTimeFormatter.ofPattern("dd.MM.yyyy."));
}           catch(DateTimeParseException e) {
    JOptionPane.showMessageDialog(this, "Datum mora biti u formatu dd.MM.yyyy.","Greska",JOptionPane.ERROR_MESSAGE);
    return;
}
        try{ 
           
            List<Korisnik>listaKorisnika=new LinkedList<>(Serijalizacija.deserijalizuj());
            if(!lozinka.equals(lozinkaProvera))
                throw new RuntimeException("Lozinke se ne podudaraju!");
            Korisnik k=new Korisnik();
            k.setIme(ime);
            k.setPrezime(prezime);
            k.setUserName(userName);
            k.setLozinka(lozinka);
            k.setDatumRodjenja(datum);
            listaKorisnika.add(k);
            Serijalizacija.serijalizuj(listaKorisnika);
           
            
        new PrelazNaPrijavu().setVisible(true);
        this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(panelRegistracija, e.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_dugmeRegistracijaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registracija().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dugmeRegistracija;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelRegistracija;
    private javax.swing.JPasswordField ponovniUnosLozinke;
    private javax.swing.JTextField unosDatum;
    private javax.swing.JTextField unosIme;
    private javax.swing.JPasswordField unosLozinka;
    private javax.swing.JTextField unosPrezime;
    private javax.swing.JTextField unosUserName;
    // End of variables declaration//GEN-END:variables
}
