/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package licneFinansije.gui;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import licneFinansije.KategorijaTrosak;
import licneFinansije.korisnik.Korisnik;
import licneFinansije.transakcije.Transakcija;
import licneFinansije.transakcije.Trosak.Trosak;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Strahinja
 */
public class TroskoviStranica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TroskoviStranica.class.getName());
    private final Korisnik korisnik;

    /**
     * Creates new form TroskoviStranica
     */
    public TroskoviStranica(Korisnik k) {
    initComponents();
    setResizable(false);
    this.korisnik = k;
    setLocationRelativeTo(null);
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy. HH:mm");
    for (Trosak t : korisnik.vratiTroskove().reversed()) {
        model.addRow(new Object[]{
            t.getIznosTransakcije(),
            t.getVremeTransakcije().format(formatter),
            t.getKategorija().toString(),
            t.getOpis()
        });
    }
    labelaUkupanTrosak.setText("Ukupan trošak: " + korisnik.izracunajTroskove(korisnik.vratiTroskove()) + " rsd");

    DefaultPieDataset dataset = new DefaultPieDataset();
    for (KategorijaTrosak kat : KategorijaTrosak.values()) {
        double ukupno = korisnik.vratiTroskove().stream()
                .filter(t -> t.getKategorija() == kat)
                .mapToDouble(t -> t.getIznosTransakcije())
                .sum();
        if (ukupno > 0)
            dataset.setValue(kat.toString(), ukupno);
    }
    JFreeChart chart = ChartFactory.createPieChart("Troškovi po kategoriji", dataset, true, true, false);
    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(panelDijagram.getPreferredSize());
    panelDijagram.setLayout(new java.awt.BorderLayout());
    panelDijagram.add(chartPanel, java.awt.BorderLayout.CENTER);
    panelDijagram.revalidate();
    PiePlot plot = (PiePlot) chart.getPlot();
    plot.setLabelGenerator(null);
    plot.setBackgroundPaint(new java.awt.Color(247, 250, 254));
    chart.setBackgroundPaint(new java.awt.Color(247, 250, 254));
    chartPanel.setBackground(new java.awt.Color(247, 250, 254));
    panelDijagram.setBackground(new java.awt.Color(247, 250, 254));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        unosDatumOd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        unosDatumDo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        CBKategorije = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelaUkupanTrosak = new javax.swing.JLabel();
        panelDijagram = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel1.setBackground(new java.awt.Color(247, 250, 254));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 700));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Analizirajte svoje troškove");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Datum od:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setText("Datum do:");

        jButton1.setText("prikaži");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("filtriraj");
        jButton2.setActionCommand("filtriraj za izabranu kategoriju");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        CBKategorije.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HRANA I PIĆE", "ZABAVA", "TROŠKOVI ŽIVOTA", "POKLONI", "ŠTEDNJA", "OSTALO" }));

        jButton3.setText("Resetuj filtere");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Iznos", "Datum i vreme", "Kategorija", "Opis"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        labelaUkupanTrosak.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        labelaUkupanTrosak.setText("jLabel4");

        javax.swing.GroupLayout panelDijagramLayout = new javax.swing.GroupLayout(panelDijagram);
        panelDijagram.setLayout(panelDijagramLayout);
        panelDijagramLayout.setHorizontalGroup(
            panelDijagramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );
        panelDijagramLayout.setVerticalGroup(
            panelDijagramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelaUkupanTrosak)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(panelDijagram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(unosDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CBKategorije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unosDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jButton2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(unosDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unosDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBKategorije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(12, 12, 12)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDijagram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(labelaUkupanTrosak)
                .addGap(113, 113, 113))
        );

        jMenu1.setText("Početna");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Prihodi");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Troškovi");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
       new PrihodiStranica(korisnik).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
         new Home(korisnik).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String stringKategorije = CBKategorije.getSelectedItem().toString();
        stringKategorije=stringKategorije.replaceAll(" ", "_");
    KategorijaTrosak kategorija = KategorijaTrosak.valueOf(stringKategorije);
    List<Trosak> lista = korisnik.filtrirajTroskovePoKategoriji(kategorija);
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy. HH:mm");
    for (Trosak t : lista.reversed()) {
        model.addRow(new Object[]{
            t.getIznosTransakcije(),
            t.getVremeTransakcije().format(formatter),
            t.getKategorija().toString().replace("_", " "),
            t.getOpis()
        });
    }
    labelaUkupanTrosak.setText("Ukupan trošak: " + korisnik.izracunajTroskove(lista) + " rsd");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy. HH:mm");
    for (Trosak t : korisnik.vratiTroskove().reversed()) {
        model.addRow(new Object[]{
            t.getIznosTransakcije(),
            t.getVremeTransakcije().format(formatter),
            t.getKategorija().toString().replace("_", " "),
            t.getOpis()
        });
    }
    labelaUkupanTrosak.setText("Ukupan trošak: " + korisnik.izracunajTroskove(korisnik.vratiTroskove()) + " rsd");
    unosDatumDo.setText(null);
    unosDatumOd.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String datumTekst1 = unosDatumOd.getText();
    String datumTekst2 = unosDatumDo.getText();
    LocalDate datumOd = null;
    LocalDate datumDo = null;
    try {
        datumOd = LocalDate.parse(datumTekst1, DateTimeFormatter.ofPattern("dd.MM.yyyy."));
        datumDo = LocalDate.parse(datumTekst2, DateTimeFormatter.ofPattern("dd.MM.yyyy."));
    } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this, "Datum mora biti u formatu dd.MM.yyyy.", "Greska", JOptionPane.ERROR_MESSAGE);
        return;
    }
    List<Trosak> lista = korisnik.filtrirajTroskoveZaVremenskiInterval(datumOd, datumDo);
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy. HH:mm");
    for (Trosak t : lista.reversed()) {
        model.addRow(new Object[]{
            t.getIznosTransakcije(),
            t.getVremeTransakcije().format(formatter),
            t.getKategorija().toString().replace("_", " "),
            t.getOpis()
        });
    }
    labelaUkupanTrosak.setText("Ukupan trošak: " + korisnik.izracunajTroskove(lista) + " rsd");

    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBKategorije;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelaUkupanTrosak;
    private javax.swing.JPanel panelDijagram;
    private javax.swing.JTextField unosDatumDo;
    private javax.swing.JTextField unosDatumOd;
    // End of variables declaration//GEN-END:variables
}
